controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - end_effector_joint
initial:  # Define initial robot poses per group
  - group: robot_arm
    pose: rest