controller_list:
  - name: robot_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - end_effector_joint